//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPvSpec) DeepCopyInto(out *LocalPvSpec) {
	*out = *in
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(corev1.VolumeNodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	out.Capacity = in.Capacity.DeepCopy()
	if in.LocalVolumeSource != nil {
		in, out := &in.LocalVolumeSource, &out.LocalVolumeSource
		*out = new(corev1.LocalVolumeSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPvSpec.
func (in *LocalPvSpec) DeepCopy() *LocalPvSpec {
	if in == nil {
		return nil
	}
	out := new(LocalPvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPvStatus) DeepCopyInto(out *LocalPvStatus) {
	*out = *in
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPvStatus.
func (in *LocalPvStatus) DeepCopy() *LocalPvStatus {
	if in == nil {
		return nil
	}
	out := new(LocalPvStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublisherDeptSpec) DeepCopyInto(out *PublisherDeptSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublisherDeptSpec.
func (in *PublisherDeptSpec) DeepCopy() *PublisherDeptSpec {
	if in == nil {
		return nil
	}
	out := new(PublisherDeptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublisherDeptStatus) DeepCopyInto(out *PublisherDeptStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublisherDeptStatus.
func (in *PublisherDeptStatus) DeepCopy() *PublisherDeptStatus {
	if in == nil {
		return nil
	}
	out := new(PublisherDeptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSet) DeepCopyInto(out *StoreSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSet.
func (in *StoreSet) DeepCopy() *StoreSet {
	if in == nil {
		return nil
	}
	out := new(StoreSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSetList) DeepCopyInto(out *StoreSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoreSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSetList.
func (in *StoreSetList) DeepCopy() *StoreSetList {
	if in == nil {
		return nil
	}
	out := new(StoreSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoreSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSetSpec) DeepCopyInto(out *StoreSetSpec) {
	*out = *in
	in.Volume.DeepCopyInto(&out.Volume)
	in.Store.DeepCopyInto(&out.Store)
	in.Publisher.DeepCopyInto(&out.Publisher)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSetSpec.
func (in *StoreSetSpec) DeepCopy() *StoreSetSpec {
	if in == nil {
		return nil
	}
	out := new(StoreSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreSetStatus) DeepCopyInto(out *StoreSetStatus) {
	*out = *in
	out.VolumeStatus = in.VolumeStatus
	in.StoreStatus.DeepCopyInto(&out.StoreStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreSetStatus.
func (in *StoreSetStatus) DeepCopy() *StoreSetStatus {
	if in == nil {
		return nil
	}
	out := new(StoreSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreStatefulSetSpec) DeepCopyInto(out *StoreStatefulSetSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreStatefulSetSpec.
func (in *StoreStatefulSetSpec) DeepCopy() *StoreStatefulSetSpec {
	if in == nil {
		return nil
	}
	out := new(StoreStatefulSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreStatefulSetStatus) DeepCopyInto(out *StoreStatefulSetStatus) {
	*out = *in
	in.Workload.DeepCopyInto(&out.Workload)
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreStatefulSetStatus.
func (in *StoreStatefulSetStatus) DeepCopy() *StoreStatefulSetStatus {
	if in == nil {
		return nil
	}
	out := new(StoreStatefulSetStatus)
	in.DeepCopyInto(out)
	return out
}
